### ISSUE TITLE
Populate Fields in Edit Profile Page

### ISSUE THREAD

**Issue by hanhossain** [ahanufhossain/CSE360-project#16]
The fields in Edit Profile Page should populate with the user's current information (right now they all show up blank)

**Comment by emmberk** [comment]
I made some methods in the controller to update the patient page, the doctor page, and the add patient page, whenever it switches to those pages. The variables (titles, etc.) should be updates in these methods. They're at the bottom of the controller class and called a few times each throughout all of the button listeners when it switches to that page.

We need to update the fields for all of the other pages too, not just in the edit profile page!

I think that Josh was supposed to do this, but I might be wrong. I'm doing the array junk, but somebody was supposed to do all of the stuff. It might already be done. I'm not sure.

**Comment by hanhossain** [comment]
Fixed.
