### ISSUE TITLE
Bug Compilaton

### ISSUE THREAD

**Issue by awlew** [ahanufhossain/CSE360-project#17]
### Registration

Can complete registration if any fields are not filled out
- [x] Fixed

Can register as same user (Duplicates username and information)
- [x] Fixed

Can register with same user of different info
- [x] Fixed
### Docter Add Patient

Can Add multiple identical patients (I can have 2 Dingus Pingus with the same username of dingus, DOB, etc). 
Suggestion: for loop to check if it's already been added in the list.
- [x] Fixed
### Doctor Checking patient page

Cannot add a new entry for a patient
- [x] Fixed
### Doctor edit profile

Able to submit a null or blank section.
- [x] Fixed

**Comment by hanhossain** [comment]
All fixed, code pushed.
